### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by ZeroPointEnergy** [mmz-srf/puppet-rkhunter#19]
Would it be possible to get a new release of the module which includes the RTKT_FILE_WHITELIST fix? Would be nice if we can consume that over the puppet forge again.

**Comment by mms-gianni** [comment]
Sure. I need a moment to have a closer look on all the changes.

**Comment by ZeroPointEnergy** [comment]
Is there is anything left to do for a new release I can help you with? Fixed the test in a pull request and they seem to run fine. Sorry to bother you again :-)

**Comment by tykeal** [comment]
I would like to add my vote to getting a new version released! I've been deploying directly off of a git ref just so I could use it.

**Comment by ZeroPointEnergy** [comment]
I forked it an released it on the forge if you are interested: https://forge.puppetlabs.com/puzzleitc/rkhunter
