### ISSUE TITLE
Module maintainers

### ISSUE THREAD

**Issue by alexjfisher** [mmz-srf/puppet-rkhunter#27]
Hi!

This module hasn't had a forge release in a number of years and I'm interested to know if you would like [Vox Pupuli](https://voxpupuli.org) to help with maintaining it going forwards.

There are a a handful of forks already, but I think it'd be great if there was a de facto 'official' version that received regular updates and releases.

Thanks!

I'd also appreciate the thoughts of those involved with some of the other forks.
@itmanagerro @ZeroPointEnergy @pgassmann ??

**Comment by pgassmann** [comment]
I support the maintenance by VoxPupuli. @ZeroPointEnergy and I are from the same company, Puzzle ITC

**Comment by ZeroPointEnergy** [comment]
I agree, it would make total sense to move this to Vox Pupuli.

**Comment by bastelfreak** [comment]
Hi @ZeroPointEnergy. Sorry that this got lost under our radar. I sent you an invitation to the Vox Pupuli org. If you accept that, you're able to migrate the repository. Our migration guide is documented on our website: https://voxpupuli.org/docs/migrate_module/

please ping me here or on slack or IRC if you've questions.

**Comment by ZeroPointEnergy** [comment]
@bastelfreak Thanks for the invitation.

I don't have access to this repository, but our fork at https://github.com/puzzle/puppet-rkhunter is more recent anyway. Is it ok if we use that one as a starting point?

**Comment by bastelfreak** [comment]
@ZeroPointEnergy sounds good to me. Do you want to start migrating the repository?

**Comment by alexjfisher** [comment]
@ZeroPointEnergy Hi!  We are going to pull your changes. It's probably best to fork this repo (so the VP repo doesn't end up showing as a fork of a fork), and then cherry-pick your commits back into it.

That's pretty much what I started back in the spring in a branch of fork I created. https://github.com/alexjfisher/puppet-rkhunter/commits/alexjfisher

**Comment by alexjfisher** [comment]
or... as @bastelfreak suggests, *migrating* your repository would have the same effect, but then you'd need to refork it if you ever wanted to start opening new PRs etc.

**Comment by bastelfreak** [comment]
@ZeroPointEnergy sounds good to me. Do you want to start migrating your repository to Vox Pupuli?

**Comment by alexjfisher** [comment]
That's odd... github is displaying the last two comments out of order.  I was replying to @bastelfreak suggestion, but that's not at all clear anymore!

**Comment by bastelfreak** [comment]
Hi people. We are going to fork this repository to Vox Pupuli. You are all most welcome to contribute there or get merge permissions.

**Comment by claudio-walser** [comment]
4 Years later:
You guys are awesome, thank you very much for taking care of this. Very much appreciated :+1:
